name: Docker Image CI

on: []
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Build and export
       uses: docker/build-push-action@v5
       with:
          context: .
          tags: equio_front:latest
          outputs: type=docker,dest=/tmp/equio_front.tar
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
          name: equio_front
          path: /tmp/equio_front.tar
