name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Build and export
       uses: docker/build-push-action@v5
       with:
          context: .
          tags: equio:latest
          outputs: type=docker,dest=/tmp/equio.tar
     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
          name: equio
          path: /tmp/equio.tar
